name: reflect_framework
homepage: https://github.com/efficientyboosters/reflect_framework
repository: https://github.com/efficientyboosters/reflect_framework
documentation: https://github.com/efficientyboosters/reflect_framework/wiki
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+3
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.2
  flutter_typeahead: ^2.0.0
  flutter_shine: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_config: ^0.4.5
  build_runner: ^1.10.12
  code_builder: ^3.5.0
  recase: ^3.0.1
  test: ^1.15.7
  source_gen: ^0.9.10+1
  dart_code: ^0.0.5
  build: ^1.6.2
  quiver: ^2.1.5
  collection: ^1.14.13
  plural_noun: ^0.0.2



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # TODO: Needed for l10n:    generate: true
  # but this breaks build_runner, see: https://github.com/dart-lang/build/issues/2835

  uses-material-design: true

  assets:
    - assets/my_first_app.png

  module:
    androidX: true
    androidPackage: nth.reflect.reflect_framework
    iosBundleIdentifier: nth.reflect.reflectFramework
