/// This code is generated by [ReflectInfoBuilder].
/// Do not modify or remove this code!
/// Regenerate it if needed using the following command: flutter packages pub run build_runner build lib --delete-conflicting-outputs
import '../core/service_class_info.dart' as _i1;
import '../domain/acme_domain.dart' as _i2;
import '../domain/domain_objects.dart' as _i3;
import '../main.dart' as _i4;
import 'reflect_gui.dart' as _i5;

class ApplicationInfo {
  String get displayName {
    return 'My first app';
  }

  String get titleImage {
    return 'assets/my_first_app.png';
  }

  String get description {
    return null;
  }

  String get homePage {
    return 'https://github.com/reflect-framework/flutter-reflect-framework';
  }

  String get documentation {
    return null;
  }

  List<String> get authors {
    return ['Nils ten Hoeve'];
  }
}

class AcmeDomainProduct extends _i1.ServiceClassInfo {
  final _i2.Product serviceObject = _i2.Product();

  String get displayName {
    return 'Product';
  }
}

class AcmeDomainTranslations extends _i1.ServiceClassInfo {
  final _i2.Translations serviceObject = _i2.Translations.forThisApp();

  String get displayName {
    return 'Translations';
  }
}

class AcmeDomainTranslationsEn extends _i1.ServiceClassInfo {
  final _i2.TranslationsEn serviceObject = _i2.TranslationsEn();

  String get displayName {
    return 'Translations en';
  }
}

class DomainObjectsPayment extends _i1.ServiceClassInfo {
  final _i3.Payment _serviceObject = _i3.Payment();

  Object get serviceObject => _serviceObject;

  String get displayName => 'Payments';

  double get order => 500;
}

class DomainObjectsCardDetails extends _i1.ServiceClassInfo {
  final _i3.CardDetails serviceObject = _i3.CardDetails();

  String get displayName {
    return 'Card details';
  }
}

class DomainObjectsAddress extends _i1.ServiceClassInfo {
  final _i3.Address serviceObject = _i3.Address();

  String get displayName {
    return 'Address';
  }
}

class DomainObjectsPersonService extends _i1.ServiceClassInfo {
  final _i3.PersonService serviceObject = _i3.PersonService();

  String get displayName {
    return 'Person service';
  }
}

class DomainObjectsPerson extends _i1.ServiceClassInfo {
  final _i3.Person serviceObject = _i3.Person('', '');

  String get displayName {
    return 'Person';
  }
}

class MainMyFirstApp extends _i1.ServiceClassInfo {
  final _i4.MyFirstApp serviceObject = _i4.MyFirstApp();

  String get displayName {
    return 'My first app';
  }
}

class ReflectGuiTabsIcon extends _i1.ServiceClassInfo {
  final _i5.TabsIcon serviceObject = _i5.TabsIcon();

  String get displayName {
    return 'Tabs icon';
  }
}
