import 'package:flutter/material.dart' as _i5;
import 'package:flutter/widgets.dart' as _i4;
import 'package:provider/provider.dart' as _i6;
import 'package:reflect_framework/core/action_method_info.dart' as _i3;
import 'package:reflect_framework/core/application_info.dart' as _i1;
import 'package:reflect_framework/core/service_class_info.dart' as _i2;
import 'package:reflect_framework/domain/domain_objects.dart' as _i10;
import 'package:reflect_framework/gui/gui_tab.dart' as _i7;
import 'package:reflect_framework/gui/gui_tab_form.dart' as _i9;
import 'package:reflect_framework/gui/gui_tab_table.dart' as _i8;

/// This code is generated by [ApplicationInfoBuilder]
/// Do not modify or remove this code!
/// Regenerate it if needed using the following command: flutter packages pub run build_runner build lib --delete-conflicting-outputs
class ReflectApplicationInfo implements _i1.ApplicationInfo {
  @override
  String get name => 'My first app';
  @override
  String get description => '';
  @override
  String get titleImage => 'assets/my_first_app.png';
  @override
  String get homePage =>
      'https://github.com/efficientyboosters/reflect_framework';
  @override
  String get documentation =>
      'https://github.com/efficientyboosters/reflect_framework/wiki';
  @override
  List<_i2.ServiceClassInfo> get serviceClassInfos => [
        ActionMethodParameterFactoryTestActionMethodParameterFactoryTestServiceInfo$(),
        DomainObjectsPersonServiceInfo$()
      ];
}

class ActionMethodParameterFactoryTestActionMethodParameterFactoryTestServiceInfo$
    extends _i2.ServiceClassInfo {
  @override
  String get name => 'Action method parameter factory tests';
  @override
  String get description => '';
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  List<_i3.ActionMethodInfo> get actionMethodInfos => [
        ActionMethodParameterFactoryTestServiceNoParameterInfo$(),
        ActionMethodParameterFactoryTestServiceNoParameterFactoryInfo$(),
        ActionMethodParameterFactoryTestServiceStringParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceBoolParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceIntParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceDoubleParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceDateTimeParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceListParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceSetParameterFactoryAnnotationInfo$(),
        ActionMethodParameterFactoryTestServiceMapParameterFactoryAnnotationInfo$()
      ];
}

class ActionMethodParameterFactoryTestServiceNoParameterInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithoutParameter {
  @override
  String get name => 'No parameter';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i4.BuildContext context) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceNoParameterFactoryInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithoutParameter {
  @override
  String get name => 'No parameter factory';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i4.BuildContext context) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceStringParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'String parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  String _createParameter() => '';
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceBoolParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Bool parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  bool _createParameter() => true;
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceIntParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Int parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  int _createParameter() => 0;
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceDoubleParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Double parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  double _createParameter() => 0.0;
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceDateTimeParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Date time parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  DateTime _createParameter() => DateTime.now();
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceListParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'List parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  List<dynamic> _createParameter() => [];
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceSetParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Set parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  Set<dynamic> _createParameter() => {};
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class ActionMethodParameterFactoryTestServiceMapParameterFactoryAnnotationInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Map parameter factory annotation';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  Map<dynamic, dynamic> _createParameter() => {};
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class DomainObjectsPersonServiceInfo$ extends _i2.ServiceClassInfo {
  @override
  String get name => 'People';
  @override
  String get description => '';
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  List<_i3.ActionMethodInfo> get actionMethodInfos => [
        PersonServiceAllPersonsInfo$(),
        PersonServiceFindPersonsInfo$(),
        PersonServiceEditInfo$(),
        PersonServiceRemoveInfo$(),
        PersonServiceAddNewInfo$(),
        PersonServiceSendEmailInfo$(),
        PersonServiceLogoutInfo$()
      ];
}

class PersonServiceAllPersonsInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithoutParameter {
  @override
  String get name => 'All persons';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.table_chart_sharp;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i8.TableExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i4.BuildContext context) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceFindPersonsInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Find persons';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.table_chart_sharp;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i8.TableExampleTabFactory().create(this);
    tabs.add(tab);
  }

  String _createParameter() => '';
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceEditInfo$
    implements _i3.StartWithParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Edit';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context, Object parameterValue) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceRemoveInfo$
    implements _i3.StartWithParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Remove';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context, Object parameterValue) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceAddNewInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Add new';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.table_rows_sharp;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i9.FormExampleTabFactory().create(this);
    tabs.add(tab);
  }

  _i10.Person _createParameter() => _i10.Person();
  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceSendEmailInfo$
    implements _i3.StartWithParameter, _i3.InvokeWithParameter {
  @override
  String get name => 'Send email';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context, Object parameterValue) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
  @override
  void invokeMethodAndProcessResult(
      _i4.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }
}

class PersonServiceLogoutInfo$
    implements _i3.StartWithoutParameter, _i3.InvokeWithoutParameter {
  @override
  String get name => 'Logout';
  @override
  String get description => '';
  @override
  _i4.IconData get icon => _i5.Icons.lens;
  @override
  bool get visible => true;
  @override
  double get order => 100.0;
  @override
  void start(_i4.BuildContext context) {
    var tabs = _i6.Provider.of<_i7.Tabs>(context, listen: false);
    var tab = _i7.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i4.BuildContext context) {
    // TODO: IMPLEMENT
  }
}
