import 'package:flutter/material.dart' as _i6;
import 'package:flutter/widgets.dart' as _i5;
import 'package:provider/provider.dart' as _i7;
import 'package:reflect_framework/core/action_method_info.dart' as _i4;
import 'package:reflect_framework/core/application_info.dart' as _i1;
import 'package:reflect_framework/core/service_class_info.dart' as _i2;
import 'package:reflect_framework/domain/action_method_parameter_factory_test.dart'
    as _i3;
import 'package:reflect_framework/domain/domain_objects.dart' as _i10;
import 'package:reflect_framework/gui/action_method_parameter_processor_impl.dart';
import 'package:reflect_framework/gui/gui_tab.dart' as _i8;
import 'package:reflect_framework/gui/gui_tab_form.dart' as _i12;
import 'package:reflect_framework/gui/gui_tab_table.dart' as _i11;

import 'gui/action_method_result_processor_impl.dart' as _i9;

/// This code is generated by [ApplicationInfoBuilder]
/// Do not modify or remove this code!
/// Regenerate it if needed using the following command: flutter packages pub run build_runner build lib --delete-conflicting-outputs
class ReflectApplicationInfo implements _i1.ApplicationInfo {
  @override
  String get name => 'My first app';

  @override
  String get description => '';

  @override
  String? get titleImage => 'assets/my_first_app.png';

  @override
  String get homePage =>
      'https://github.com/efficientyboosters/reflect_framework';
  @override
  String get documentation =>
      'https://github.com/efficientyboosters/reflect_framework/wiki';
  @override
  List<_i2.ServiceClassInfo> get serviceClassInfos => [
        ActionMethodParameterFactoryTestActionMethodParameterFactoryTestServiceInfo$(),
        DomainObjectsPersonServiceInfo$()
      ];
}

class ActionMethodParameterFactoryTestActionMethodParameterFactoryTestServiceInfo$
    extends _i2.ServiceClassInfo<_i3.ActionMethodParameterFactoryTestService> {
  @override
  final serviceObject = _i3.ActionMethodParameterFactoryTestService();

  @override
  String get name => 'Action method parameter factory tests';

  @override
  String get description => '';

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  List<_i4.ActionMethodInfo> get actionMethodInfos => [
        ActionMethodParameterFactoryTestServiceNoParameterInfo$(serviceObject),
        ActionMethodParameterFactoryTestServiceNoParameterFactoryInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceStringParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceBoolParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceIntParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceDoubleParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceDateTimeParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceListParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceSetParameterFactoryAnnotationInfo$(
            serviceObject),
        ActionMethodParameterFactoryTestServiceMapParameterFactoryAnnotationInfo$(
            serviceObject)
      ];
}

class ActionMethodParameterFactoryTestServiceNoParameterInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithoutParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceNoParameterInfo$(this.methodOwner);

  @override
  String get name => 'No parameter';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i5.BuildContext context) {
    methodOwner.noParameter();
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceNoParameterFactoryInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithoutParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceNoParameterFactoryInfo$(
      this.methodOwner);

  @override
  String get name => 'No parameter factory';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i5.BuildContext context) {
    methodOwner.noParameterFactory();
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceStringParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceStringParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'String parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  String _createParameter() => '';

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.stringParameterFactoryAnnotation(parameterValue as String);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceBoolParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceBoolParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Bool parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  bool _createParameter() => true;

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.boolParameterFactoryAnnotation(parameterValue as bool);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceIntParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceIntParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Int parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  int _createParameter() => 0;

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.intParameterFactoryAnnotation(parameterValue as int);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceDoubleParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceDoubleParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Double parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  double _createParameter() => 0.0;

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.doubleParameterFactoryAnnotation(parameterValue as double);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceDateTimeParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceDateTimeParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Date time parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  DateTime _createParameter() => DateTime.now();

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.dateTimeParameterFactoryAnnotation(parameterValue as DateTime);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceListParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceListParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'List parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  List<dynamic> _createParameter() => [];

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.listParameterFactoryAnnotation(parameterValue as List<dynamic>);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceSetParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceSetParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Set parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  Set<dynamic> _createParameter() => {};

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.setParameterFactoryAnnotation(parameterValue as Set<dynamic>);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class ActionMethodParameterFactoryTestServiceMapParameterFactoryAnnotationInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i3.ActionMethodParameterFactoryTestService methodOwner;

  ActionMethodParameterFactoryTestServiceMapParameterFactoryAnnotationInfo$(
      this.methodOwner);

  @override
  String get name => 'Map parameter factory annotation';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  Map<dynamic, dynamic> _createParameter() => {};

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner
        .mapParameterFactoryAnnotation(parameterValue as Map<dynamic, dynamic>);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class DomainObjectsPersonServiceInfo$
    extends _i2.ServiceClassInfo<_i10.PersonService> {
  @override
  final serviceObject = _i10.PersonService();

  @override
  String get name => 'People';

  @override
  String get description => '';

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  List<_i4.ActionMethodInfo> get actionMethodInfos => [
        PersonServiceAllPersonsInfo$(serviceObject),
        PersonServiceFindPersonsInfo$(serviceObject),
        PersonServiceEditInfo$(serviceObject),
        PersonServiceRemoveInfo$(serviceObject),
        PersonServiceAddNewInfo$(serviceObject),
        PersonServiceSendEmailInfo$(serviceObject),
        PersonServiceLogoutInfo$(serviceObject)
      ];
}

class PersonServiceAllPersonsInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithoutParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceAllPersonsInfo$(this.methodOwner);

  @override
  String get name => 'All persons';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.table_chart_sharp;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i11.TableExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i5.BuildContext context) {
    List<_i10.Person> returnValue = methodOwner.allPersons();
    _i9.showListInTableTab(context, this, returnValue);
  }
}

class PersonServiceFindPersonsInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceFindPersonsInfo$(this.methodOwner);

  @override
  String get name => 'Find persons';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.table_chart_sharp;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    String parameterValue = '';
    editStringParameterInDialog(context, this, parameterValue);
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    List<_i10.Person> returnValue =
        methodOwner.findPersons(parameterValue as String);
    _i9.showListInTableTab(context, this, returnValue);
  }
}

class PersonServiceEditInfo$
    implements _i4.StartWithParameter, _i4.InvokeWithParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceEditInfo$(this.methodOwner);

  @override
  String get name => 'Edit';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context, Object parameterValue) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.edit(parameterValue as _i10.Person);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class PersonServiceRemoveInfo$
    implements _i4.StartWithParameter, _i4.InvokeWithParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceRemoveInfo$(this.methodOwner);

  @override
  String get name => 'Remove';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context, Object parameterValue) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.remove(parameterValue as _i10.Person);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class PersonServiceAddNewInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceAddNewInfo$(this.methodOwner);

  @override
  String get name => 'Add new';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.table_rows_sharp;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i12.FormExampleTabFactory().create(this);
    tabs.add(tab);
  }

  _i10.Person _createParameter() => _i10.Person();

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.addNew(parameterValue as _i10.Person);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class PersonServiceSendEmailInfo$
    implements _i4.StartWithParameter, _i4.InvokeWithParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceSendEmailInfo$(this.methodOwner);

  @override
  String get name => 'Send email';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context, Object parameterValue) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  void _processParameter(_i5.BuildContext context, Object parameterValue) {
    // TODO: IMPLEMENT
  }

  @override
  void invokeMethodAndProcessResult(
      _i5.BuildContext context, Object parameterValue) {
    methodOwner.sendEmail(parameterValue as _i10.Person);
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}

class PersonServiceLogoutInfo$
    implements _i4.StartWithoutParameter, _i4.InvokeWithoutParameter {
  @override
  final _i10.PersonService methodOwner;

  PersonServiceLogoutInfo$(this.methodOwner);

  @override
  String get name => 'Logout';

  @override
  String get description => '';

  @override
  _i5.IconData get icon => _i6.Icons.lens;

  @override
  bool get visible => true;

  @override
  double get order => 100.0;

  @override
  void start(_i5.BuildContext context) {
    var tabs = _i7.Provider.of<_i8.Tabs>(context, listen: false);
    var tab = _i8.ExampleTabFactory().create(this);
    tabs.add(tab);
  }

  @override
  void invokeMethodAndProcessResult(_i5.BuildContext context) {
    methodOwner.logout();
    _i9.showMethodExecutedSnackbarForMethodsReturningVoid(context, this);
  }
}
