import 'package:reflect_framework/core/reflect_meta_temp.dart';

/// [ApplicationInfo] provides all the domain meta information needed for the [ReflectGuiApplication]
/// An [GeneratedApplicationInfo] is generated by the [ApplicationInfoBuilder]

abstract class ApplicationInfo {
  String get displayName;

  String get titleImage;

  String get description;

  String get homePage;

  String get documentation;

  ///TODO replace [ServiceObjectInfo] with [{]ServiceClassInfo]
  List<ServiceObjectInfo> get serviceClasses;

//TODO List<DomainClassInfo> get domainClasses;
}
