import 'package:reflect_framework/core/domain_class_reflection.dart';

import 'item.dart';
import 'service_class_info.dart';

/// [ApplicationInfo] provides all the domain meta information needed for the [ReflectGuiApplication]
/// An [GeneratedApplicationInfo] is generated by the [ApplicationInfoBuilder]

abstract class ApplicationInfo implements Item {
  String? get titleImage;

  String get homePage;

  String get documentation;

  List<ServiceClassInfo> get serviceClassInfos;

  List<DomainClassReflection> get domainClassReflections => [];
}
