import 'package:reflect_framework/core/item.dart';
import 'package:reflect_framework/core/service_class_info.dart';

/// [ApplicationInfo] provides all the domain meta information needed for the [ReflectGuiApplication]
/// An [GeneratedApplicationInfo] is generated by the [ApplicationInfoBuilder]

abstract class ApplicationInfo implements Item {
  String get titleImage;

  String get homePage;

  String get documentation;

  List<ServiceClassInfo> get serviceClassInfos;

//TODO List<DomainClassInfo> get domainClasses;
}
