import 'package:dart_code/dart_code.dart';

import '../code_builders/info_json.dart';
import 'application_info_class_code.dart';

class ApplicationInfoLibraryCode extends Library {
  ApplicationInfoLibraryCode(ReflectJson reflectJson)
      : super(
            docComments: _createDocComments(),
            classes: createClasses(reflectJson));

  static List<DocComment> _createDocComments() => [
        DocComment.fromString(
            'This code is generated by [ApplicationInfoBuilder]'),
        DocComment.fromString('Do not modify or remove this code!'),
        DocComment.fromString(
            'Regenerate it if needed using the following command: flutter packages pub run build_runner build lib --delete-conflicting-outputs'),
      ];

  static List<Class> createClasses(ReflectJson reflectJson) =>
      [GeneratedApplicationInfoCode(reflectJson)];
}
