import 'package:dart_code/dart_code.dart';
import 'package:reflect_framework/code_builders_code/service_class_info_class.dart';

import '../code_builders/info_json.dart';
import 'application_info_class.dart';

class ApplicationInfoLibraryCode extends Library {
  ApplicationInfoLibraryCode(ReflectJson reflectJson)
      : super(
            docComments: _createDocComments(),
            classes: createClasses(reflectJson));

  static List<DocComment> _createDocComments() => [
        DocComment.fromString(
            'This code is generated by [ApplicationInfoBuilder]'),
        DocComment.fromString('Do not modify or remove this code!'),
        DocComment.fromString(
            'Regenerate it if needed using the following command: flutter pub run build_runner build --delete-conflicting-outputs'),
      ];

  static List<Class> createClasses(ReflectJson reflectJson) {
    List<Class> classes = [];
    var serviceClassInfoClasses = ServiceClassInfoClasses(reflectJson);
    classes.add(ApplicationInfoClass(reflectJson, serviceClassInfoClasses));

    for (ServiceClassInfoClass serviceClassInfoClass
        in serviceClassInfoClasses) {
      if (serviceClassInfoClass.actionMethodInfoClasses.isNotEmpty) {
        classes.add(serviceClassInfoClass);
        classes.addAll(serviceClassInfoClass.actionMethodInfoClasses);
      }
    }

    return classes;
  }
}
